resolver: lts-22.43

packages:
- .

nix:
  # pure: false
  packages:
  - zlib
  - pcre
  path:
  - "nixpkgs=/home/tom/tools/nixpkgs"

extra-deps:
# - language-rust-0.2.0.27

# - github: harpocrates/language-rust
#   commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce
