
resolver: lts-21.17

packages:
- .

nix:
  # pure: false
  packages:
  - zlib
  - pcre
  path:
  - "nixpkgs=/home/tom/tools/nixpkgs"

extra-deps:
- git: https://github.com/codedownio/myers-diff.git
  commit: 3683ab4e052347bc47eb5546361f47bcd8c0fa58

# - language-rust-0.2.0.27

# - github: harpocrates/language-rust
#   commit: 9d509c450d009cc99f1180b3f2f30247dfb1cfce
